/**:
  ros__parameters:
    camera_name: "camera_1"
    frame_id: "lucid_vision"
    pixel_format: bgr8
    serial_no: 220500927
    fps: 15
    width: 1440
    height: 930
    camera_info_url: "file:///home/leo/camera_ws/src/arena_camera/config/camera_front_half.yaml"
