/**:
  ros__parameters:
    camera_name: "camera_1"
    frame_id: "camera_top/camera_link"
    pixel_format: bgr8
    serial_no: 220300119
    fps: 15
    horizontal_binning: 4
    vertical_binning: 4
    resize_image: false
    camera_info_url: "file:///home/volt/projects/volt_drivers_ws/src/arena_camera/config/camera_front_half.yaml"
    auto_expoure: true
